source 'http://rubygems.org'

gem 'rake', '0.9.2'

gem "effin_utf8"
gem 'nanoc'
gem 'compass_twitter_bootstrap'
gem 'RedCloth'
gem "rack"
gem "mime-types"
gem "builder"
gem "nokogiri"
gem "haml"
gem "liquid"
gem "adsf"
gem 'kramdown'